--- #YAML:1.0
name: Time-Piece-ISO
version: 0.05
license: perl
distribution_type: module
requires:
  Time::Piece: 1.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Time::Piece::ISO:
    file: lib/Time/Piece/ISO.pm
    version: 0.05
generated_by: Module::Build version 0.19_05
