---
name: Time-Piece-ISO
version: 0.11
author:
  - |-
    David Wheeler <david@justatheory.com>, extending Matt Seargent's
    <matt@seargent.org> L<Time::Piece|Time::Piece> module.
abstract: ISO 8601 Subclass of Time::Piece
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  Time::Piece: 1.01
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Time::Piece::ISO:
    file: lib/Time/Piece/ISO.pm
    version: 0.11
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
